<?xml version="1.0" encoding="utf-8"?><Database Name="climoo" Class="MooCoreSqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=climoo-tc;Integrated Security=True" SettingsObjectName="Kayateia.Climoo.MooCore.Properties.Settings" SettingsPropertyName="climooConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Mob" Member="Mobs">
    <Type Name="Mob">
      <Column Name="id" AutoSync="Never" Type="System.Int32" DbType="Int IDENTITY NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="location" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pathid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="checkpoint" Type="System.Int32" CanBeNull="false" />
      <Column Name="objectid" Type="System.Int32" CanBeNull="false" />
      <Association Name="Mob_Mob" Member="Mobs" ThisKey="objectid" OtherKey="location" Type="Mob" />
      <Association Name="Mob_Mob1" Member="Mobs1" ThisKey="objectid" OtherKey="parent" Type="Mob" />
      <Association Name="Mob_Verb" Member="Verbs" ThisKey="id" OtherKey="object" Type="Verb" />
      <Association Name="Mob_Attribute" Member="Attributes" ThisKey="id" OtherKey="object" Type="Attribute" />
      <Association Name="Mob_Mob" Member="Mob1" ThisKey="location" OtherKey="objectid" Type="Mob" IsForeignKey="true" />
      <Association Name="Mob_Mob1" Member="Mob2" ThisKey="parent" OtherKey="objectid" Type="Mob" IsForeignKey="true" />
      <Association Name="Checkpoint_Mob" Member="Checkpoint1" ThisKey="checkpoint" OtherKey="id" Type="Checkpoint" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Verb" Member="Verbs">
    <Type Name="Verb">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="object" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Mob_Verb" Member="Mob" ThisKey="object" OtherKey="id" Type="Mob" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.World" Member="Worlds">
    <Type Name="World">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="intvalue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="strvalue" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="checkpoint" Type="System.Int32" CanBeNull="false" />
      <Association Name="Checkpoint_World" Member="Checkpoint1" ThisKey="checkpoint" OtherKey="id" Type="Checkpoint" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Attribute" Member="Attributes">
    <Type Name="Attribute">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="textcontents" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="datacontents" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mimetype" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="object" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Mob_Attribute" Member="Mob" ThisKey="object" OtherKey="id" Type="Mob" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="Checkpoints">
    <Type Name="Checkpoint">
      <Column Name="id" AutoSync="Never" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="time" Type="System.DateTimeOffset" CanBeNull="false" />
      <Column Name="name" Type="System.String" CanBeNull="true" />
      <Association Name="Checkpoint_Mob" Member="Mobs" ThisKey="id" OtherKey="checkpoint" Type="Mob" />
      <Association Name="Checkpoint_World" Member="Worlds" ThisKey="id" OtherKey="checkpoint" Type="World" />
    </Type>
  </Table>
</Database>